%% Compile Osprey
function CompileOspreyStandalone(OutputDir,SPM12Dir,WidgetsDir,GUILayoutDir)
%% CompileOspreyStandalone(OutputDir,SPM12Dir,WidgetsDir,GUILayoutDir)
%   This function compiles Osprey including a command window version, a
%   HBCD specific version with reduced basis sets, and a GUI version. The
%   compilation includes SPM12 for coregistration and segmentation. The GUI
%   version is only compiled if the path to the Widgets and the GUI Layout
%   Toolboxes is supplied. For the compilation to work you have to prepare
%   Osprey the following way:
% 
%   The easiest way is to search through all files in the Osprey folder looking for the follwing terms and subsequently comment out those lines:
% 
%   addpath
%
% 	        1 x in osp_fitUnedited.m
% 	        1 x in osp_fitInitialise.m
% 
%   Comment out the whole 2. GET SPMPATH AND TOOLBOXES sessuib in osp_Toolbox_Check.m
% 
%   In addtion you should remove the startup.m file from your Matlab folder as this interfers with the compilation and results in non-crashing errors in the compiled version.
%   Make sure to run a clear all before runnning the script.
% 
%   Add SPM12 to your path and include all subfolders!
% 
%   Update the version number.
% 
%
%   USAGE:
%       CompileOspreyStandalone(OutputDir,SPM12Dir,WidgetsDir,GUILayoutDir)
%
%   INPUTS:
%       OutputDir    = output directory.
%       SPM12Dir     = path to SPM12.
%       WidgetsDir   = path to the Widgets Toolbox.
%       GUILayoutDir = path to the GUI Layout Toolbox.
%
%   OUTPUTS:
%       Compiled Osprey.
%
%   AUTHOR:
%       Dr. Helge Zoellner (Johns Hopkins University, 2022-05-19)
%       hzoelln2@jhmi.edu
%
%   CREDITS:
%       This code is based on numerous functions from the FID-A toolbox by
%       Dr. Jamie Near (McGill University)
%       https://github.com/CIC-methods/FID-A
%       Simpson et al., Magn Reson Med 77:23-33 (2017)
%
%   HISTORY:
%       2022-05-19: First version of the code.


%% 0. Setup folder strucutre
if ~exist(OutputDir)
    mkdir(OutputDir); 
end
OutputDirCmd = fullfile(OutputDir,'CommandLine');
OutputDirHBCD = fullfile(OutputDir,'HBCD');
OutputDirGUI = fullfile(OutputDir,'GUI');
if exist(OutputDirCmd,'Dir')
    rmdir(OutputDirCmd,'s');
end
if exist(OutputDirHBCD,'Dir')
    rmdir(OutputDirHBCD,'s');
end
if exist(OutputDirGUI,'Dir')
    rmdir(OutputDirGUI,'s');
end
mkdir(OutputDirCmd);
mkdir(OutputDirHBCD);
mkdir(OutputDirGUI);

[SettingsDir,~,~] = fileparts(which('OspreySettings.m'));
AllDirs      = strsplit(SettingsDir, filesep);
OspreyDir       = strjoin(AllDirs(1:end-1), filesep); % parent folder (= Osprey directory)

%% 1. Prepare SPM12 for compilation
% The code is copied from spm_make_standalone.m
%-Input arguments
%--------------------------------------------------------------------------
contentsver = '';

%==========================================================================
%-Static listing of SPM toolboxes
%==========================================================================
fid = fopen(fullfile(SPM12Dir,'config','spm_cfg_static_tools.m'),'wt');
fprintf(fid,'function values = spm_cfg_static_tools\n');
fprintf(fid,...
    '%% Static listing of all batch configuration files in the SPM toolbox folder\n');
%-Get the list of toolbox directories
tbxdir = fullfile(SPM12Dir,'toolbox');
d = [tbxdir; cellstr(spm_select('FPList',tbxdir,'dir'))];
ft = {};
%-Look for '*_cfg_*.m' files in these directories
for i=1:numel(d)
    fi = spm_select('List',d{i},'.*_cfg_.*\.m$');
    if ~isempty(fi)
        ft = [ft(:); cellstr(fi)];
    end
end
%-Create code to insert toolbox config
if isempty(ft)
    ftstr = '';
else
    ft = spm_file(ft,'basename');
    ftstr = sprintf('%s ', ft{:});
end
fprintf(fid,'values = {%s};\n', ftstr);
fclose(fid);

%==========================================================================
%-Static listing of batch application initialisation files
%==========================================================================
cfg_util('dumpcfg');

%==========================================================================
%-Duplicate Contents.m in Contents.txt for use in spm('Ver')
%==========================================================================
sts = copyfile(fullfile(SPM12Dir,'Contents.m'),...
               fullfile(SPM12Dir,'Contents.txt'));
if ~sts, warning('Copy of Contents.m failed.'); end
if ~isempty(contentsver)
    % Format: 'xxxx (SPMx) dd-mmm-yyyy'
    f = fileread(fullfile(spm('Dir'),'Contents.txt'));
    f = regexprep(f,'% Version \S+ \S+ \S+',['% Version ' contentsver]);
    fid = fopen(fullfile(spm('Dir'),'Contents.txt'),'w');
    fprintf(fid,'%s',f);
    fclose(fid);
end

%==========================================================================
%-Trim FieldTrip
%==========================================================================
d = fullfile(SPM12Dir,'external','fieldtrip','compat');
d = cellstr(spm_select('FPList',d,'dir'));
for i=1:numel(d)
    f = spm_file(d{i},'basename');
    nrmv = strncmp(f,'matlablt',8);
    if nrmv
        [dummy,I] = sort({f(9:end),version('-release')});
        nrmv = I(1) == 2;
    end
    if ~nrmv
        [sts, msg] = rmdir(d{i},'s');
    end
end

% Copy the License files 
copyfile(fullfile(OspreyDir,'LICENSE.md'),fullfile(OutputDirCmd,'OSPREY_LICENSE.md'));
copyfile(fullfile(OspreyDir,'LICENSE.md'),fullfile(OutputDirHBCD,'OSPREY_LICENSE.md'));
copyfile(fullfile(OspreyDir,'LICENSE.md'),fullfile(OutputDirGUI,'OSPREY_LICENSE.md'));

copyfile(fullfile(SPM12Dir,'LICENCE.txt'),fullfile(OutputDirCmd,'SPM12_LICENCE.txt'));
copyfile(fullfile(SPM12Dir,'LICENCE.txt'),fullfile(OutputDirHBCD,'SPM12_LICENCE.txt'));
copyfile(fullfile(SPM12Dir,'LICENCE.txt'),fullfile(OutputDirGUI,'SPM12_LICENCE.txt'));

copyfile(fullfile(SPM12Dir,'Contents.txt'),fullfile(OutputDirCmd,'SPM12_Contents.txt'));
copyfile(fullfile(SPM12Dir,'Contents.txt'),fullfile(OutputDirHBCD,'SPM12_Contents.txt'));
copyfile(fullfile(SPM12Dir,'Contents.txt'),fullfile(OutputDirGUI,'SPM12_Contents.txt'));

%% 2. HBCD export
% Compile a HBCD specific version of Osprey (Reduced number of basis sets)

appFile = fullfile(OspreyDir, 'utilities','RunOspreyJob.m');

opts = compiler.build.StandaloneApplicationOptions(appFile,...
    'OutputDir',OutputDirHBCD,...
    'ExecutableIcon',fullfile(OspreyDir, 'graphics','osprey.gif'),...
    'ExecutableSplashScreen',fullfile(OspreyDir, 'graphics','osprey.gif'),...
    'ExecutableVersion','2.2.0',...
    'ExecutableName','OspreyHBCD',...
    'AdditionalFiles',{ fullfile(SPM12Dir),...
                       fullfile(OspreyDir,'coreg'),...
                       fullfile(OspreyDir,'fit','osp_editControlParameters.m'),... Include the fit scripts manually 
                       fullfile(OspreyDir,'fit','osp_extract_minmax_fit.m'),...
                       fullfile(OspreyDir,'fit','osp_fit_Quality.m'),...
                       fullfile(OspreyDir,'fit','osp_fitHERCULES.m'),...
                       fullfile(OspreyDir,'fit','osp_fitHERMES.m'),...
                       fullfile(OspreyDir,'fit','osp_fitInitialise.m'),...
                       fullfile(OspreyDir,'fit','osp_fitMEGA.m'),...
                       fullfile(OspreyDir,'fit','osp_fitMultiVoxel.m'),...
                       fullfile(OspreyDir,'fit','osp_fitUnEdited.m'),...
                       fullfile(OspreyDir,'fit','osp_fitWater.m'),...
                       fullfile(OspreyDir,'fit','osp_spiral.m'),...
                       fullfile(OspreyDir,'fit','osp_writelcm_control.m'),...
                       fullfile(OspreyDir,'fit','OspreyFit.m'),...
                       fullfile(OspreyDir,'fit','basissets','3T','philips','hercules-press','basis_philips_hercules-press.mat'),... Include the basis sets manually 
                       fullfile(OspreyDir,'fit','basissets','3T','siemens','hercules-press','basis_siemens_hercules-press.mat'),...
                       fullfile(OspreyDir,'fit','basissets','3T','ge','hercules-press','basis_ge_hercules-press.mat'),...
                       fullfile(OspreyDir,'fit','basissets','3T','philips','unedited','press','35','basis_philips_press35.mat'),...
                       fullfile(OspreyDir,'fit','basissets','3T','siemens','unedited','press','35','basis_siemens_press35.mat'),...
                       fullfile(OspreyDir,'fit','basissets','3T','ge','unedited','press','35','basis_ge_press35.mat'),...
                       fullfile(OspreyDir,'graphics'),...
                       fullfile(OspreyDir,'job'),...
                       fullfile(OspreyDir,'libraries'),...
                       fullfile(OspreyDir,'load'),...
                       fullfile(OspreyDir,'overview'),...
                       fullfile(OspreyDir,'plot'),...
                       fullfile(OspreyDir,'process'),...
                       fullfile(OspreyDir,'quantify'),...
                       fullfile(OspreyDir,'seg'),...
                       fullfile(OspreyDir,'settings'),...
                       fullfile(OspreyDir,'utilities'),...
                       fullfile(OspreyDir,'CODE_OF_CONDUCT.md'),...
                       fullfile(OspreyDir,'LICENSE.md'),...
                       fullfile(OspreyDir,'README.md'),... 
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','compile_mex.m'),... We have to include the mex files manually
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.c'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexa64'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexmaci64'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexw64')},...  
    'AutoDetectDataFiles','On',...
    'TreatInputsAsNumeric','Off',...
    'Verbose','On');

compiler.build.standaloneApplication(opts);

%% 3. Command Line export
% Compile a command line version of Osprey

appFile = fullfile(OspreyDir, 'utilities','RunOspreyJob.m');

opts = compiler.build.StandaloneApplicationOptions(appFile,...
    'OutputDir',OutputDirCmd,...
    'ExecutableIcon',fullfile(OspreyDir, 'graphics','osprey.gif'),...
    'ExecutableSplashScreen',fullfile(OspreyDir, 'graphics','osprey.gif'),...
    'ExecutableVersion','2.2.0',...
    'ExecutableName','OspreyCMD',...
    'AdditionalFiles',{ fullfile(SPM12Dir),...
                       fullfile(OspreyDir,'coreg'),...
                       fullfile(OspreyDir,'fit'),...
                       fullfile(OspreyDir,'graphics'),...
                       fullfile(OspreyDir,'job'),...
                       fullfile(OspreyDir,'libraries'),...
                       fullfile(OspreyDir,'load'),...
                       fullfile(OspreyDir,'overview'),...
                       fullfile(OspreyDir,'plot'),...
                       fullfile(OspreyDir,'process'),...
                       fullfile(OspreyDir,'quantify'),...
                       fullfile(OspreyDir,'seg'),...
                       fullfile(OspreyDir,'settings'),...
                       fullfile(OspreyDir,'utilities'),...
                       fullfile(OspreyDir,'CODE_OF_CONDUCT.md'),...
                       fullfile(OspreyDir,'LICENSE.md'),...
                       fullfile(OspreyDir,'README.md'),... 
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','compile_mex.m'),... We have to include the mex files manually
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.c'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexa64'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexmaci64'),...
                       fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexw64')},...  
    'AutoDetectDataFiles','On',...
    'TreatInputsAsNumeric','Off',...
    'Verbose','On');
compiler.build.standaloneApplication(opts);

%% 4. GUI export
% Compile GUI Osprey which is only working if you supplied the path to the
% widgets and GUI Layout Toolboxes

if nargin == 4
    appFile = fullfile(OspreyDir, 'GUI','Osprey.m');
    opts = compiler.build.StandaloneApplicationOptions(appFile,...
        'OutputDir',OutputDirGUI,...
        'ExecutableIcon',fullfile(OspreyDir, 'graphics','osprey.gif'),...
        'ExecutableSplashScreen',fullfile(OspreyDir, 'graphics','osprey.gif'),...
        'ExecutableVersion','2.2.0',...
        'ExecutableName','Osprey',...
        'AdditionalFiles',{fullfile(WidgetsDir),...
                           fullfile(GUILayoutDir),...
                           fullfile(SPM12Dir),...
                           fullfile(OspreyDir,'GUI'),...
                           fullfile(OspreyDir,'coreg'),...
                           fullfile(OspreyDir,'fit'),...
                           fullfile(OspreyDir,'graphics'),...
                           fullfile(OspreyDir,'job'),...
                           fullfile(OspreyDir,'libraries'),...
                           fullfile(OspreyDir,'load'),...
                           fullfile(OspreyDir,'overview'),...
                           fullfile(OspreyDir,'plot'),...
                           fullfile(OspreyDir,'process'),...
                           fullfile(OspreyDir,'quantify'),...
                           fullfile(OspreyDir,'seg'),...
                           fullfile(OspreyDir,'settings'),...
                           fullfile(OspreyDir,'utilities'),...
                           fullfile(OspreyDir,'CODE_OF_CONDUCT.md'),...
                           fullfile(OspreyDir,'LICENSE.md'),...
                           fullfile(OspreyDir,'README.md'),... 
                           fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','compile_mex.m'),... We have to include the mex files manually
                           fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.c'),...
                           fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexa64'),...
                           fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexmaci64'),...
                           fullfile(OspreyDir,'libraries','L-BFGS-B-C','Matlab','lbfgsb_wrapper.mexw64')},...  
        'AutoDetectDataFiles','On',...
        'TreatInputsAsNumeric','Off',...
        'Verbose','On');
    
    compiler.build.standaloneApplication(opts);
end

end