function osp_add_orientation_labels_to_montage(idx_start, idx_end, slices_per_row, ...
    tile_width, tile_height, orientation_info, display_info)
%   This function adds orientation labels (L/R, A/P, S/I) to each slice 
%   in an MRSI montage display.
%
%   Places labels at the edges of each tile to indicate anatomical
%   orientation and adds an info annotation at the bottom of the figure
%   showing the view type, slice axis, and display convention.
%
%   USAGE:
%       osp_add_orientation_labels_to_montage(idx_start, idx_end, slices_per_row, ...
%           tile_width, tile_height, orientation_info, display_info);
%
%   INPUTS:
%       idx_start        = Starting index of slices to display.
%       idx_end          = Ending index of slices to display.
%       slices_per_row   = Number of slices per row in the montage.
%       tile_width       = Width of each tile in pixels.
%       tile_height      = Height of each tile in pixels.
%       orientation_info = Structure containing orientation information
%                          with field 'slice_orientation'.
%       display_info     = Structure containing display settings
%                          with field 'convention'.
%
%
%   AUTHOR:
%       Dr. Helge Zollner (Johns Hopkins University, 2021-01-06)
%       hzoelln2@jhmi.edu
%
%
%   HISTORY:
%       2026-01-06: First version of the code.
%%
    
    labels = osp_get_orientation_labels(orientation_info, display_info);
    
    label_color = [254/255, 186/255, 47/255];
    label_fontsize = 10;
    label_fontweight = 'bold';
    edge_offset = 0;
    
    num_slices = idx_end - idx_start + 1;
    
    for slice_idx = 1:num_slices
        montage_col = mod(slice_idx - 1, slices_per_row);
        montage_row = floor((slice_idx - 1) / slices_per_row);
        
        tile_left = montage_col * tile_width;
        tile_right = tile_left + tile_width;
        tile_top = montage_row * tile_height;
        tile_bottom = tile_top + tile_height;
        
        tile_center_x = (tile_left + tile_right) / 2;
        tile_center_y = (tile_top + tile_bottom) / 2;
        
        if slice_idx == 1
            % Left label
            text(tile_left + edge_offset, tile_center_y, labels.left, ...
                'Color', label_color, ...
                'FontSize', label_fontsize, ...
                'FontWeight', label_fontweight, ...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle');
        end
        
        if slice_idx == num_slices
            % Right label
            text(tile_right - edge_offset, tile_center_y, labels.right, ...
                'Color', label_color, ...
                'FontSize', label_fontsize, ...
                'FontWeight', label_fontweight, ...
                'HorizontalAlignment', 'right', ...
                'VerticalAlignment', 'middle');
        end
        
        if slice_idx == round(num_slices/2)
            % Top label
            text(tile_center_x, tile_top + edge_offset, labels.top, ...
                'Color', label_color, ...
                'FontSize', label_fontsize, ...
                'FontWeight', label_fontweight, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'bottom');
        end
        
        if slice_idx == round(num_slices/2)
            % Bottom label
            text(tile_center_x, tile_bottom + edge_offset, labels.bottom, ...
                'Color', label_color, ...
                'FontSize', label_fontsize, ...
                'FontWeight', label_fontweight, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'bottom');
        end

        if num_slices > 1
            if slice_idx == 1
                % Slice top
                text(tile_left, tile_top + edge_offset, ...
                    labels.slice_neg_label, ...
                    'Color', label_color, ...
                    'FontSize', label_fontsize, ...
                    'FontWeight', label_fontweight, ...
                    'HorizontalAlignment', 'center', ...
                    'VerticalAlignment', 'bottom');
            end
    
            if slice_idx == num_slices
                % Slice bottom
                text(tile_left, tile_top + edge_offset, ...
                    labels.slice_pos_label, ...
                    'Color', label_color, ...
                    'FontSize', label_fontsize, ...
                    'FontWeight', label_fontweight, ...
                    'HorizontalAlignment', 'center', ...
                    'VerticalAlignment', 'bottom');
            end
        end
    end
    
    % Add info annotation at bottom of figure
    ax = gca;
    ax_pos = ax.Position;
    
    convention_display = [upper(display_info.convention(1)), display_info.convention(2:end)];
    
    info_str = sprintf('%s view | Slices along %s axis | %s convention', ...
        osp_capitalize_first(orientation_info.slice_orientation), ...
        labels.slice_axis, ...
        convention_display);
    
    annotation('textbox', [ax_pos(1), 0.01, ax_pos(3), 0.03], ...
        'String', info_str, ...
        'Color', [0.8 0.8 0.8], ...
        'FontSize', 9, ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom');

  
end